### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by rubiin** [toonvanstrijp/i18n-demo#1]
I am sending exceptions from my services, how do i use It on my service

**Comment by toonvanstrijp** [comment]
I don't understand your question

**Comment by rubiin** [comment]
how do i use this on service. Like when i am throwing some exception, I have english and i want to localize it too

**Comment by toonvanstrijp** [comment]
You can use a filter for that: [https://docs.nestjs.com/exception-filters](https://docs.nestjs.com/exception-filters) catch the exception and then in your filter use the `i18nService` to translate the error message.
